# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b6e4a79cef4dee6fdb9cc3b610744f0827ca2cc9f9bdfe49e0050a26c07273d580087439c4f6e3774f62889860f96636e2b96d891ac1ff7310e28fe0a03459cf

test:
  secret_key_base: 91159635939df052864a2ab4ca0f88423ca58c268519bd0a34f1221edd574bb1b73aee40cacbb0473f4116e1b1660b54b1c4c64e86bb581bf74c3c9ca8b83192

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
